name: Template dispatch

on:
   workflow_dispatch:

jobs:
   release-pr:
      uses: OliverMKing/gerp/.github/workflows/template_dispatch.yaml@main
      with:
         repos: '["org/repo", "org2/repo"]'
